In [1]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd  
from sklearn.model_selection import train_test_split

# Credit Data

In [2]:

# Fetch dataset
default_of_credit_card_clients = fetch_ucirepo(id=350)

# Extract features (X) and target (y)
X = default_of_credit_card_clients.data.features
y = default_of_credit_card_clients.data.targets

# Metadata inspection for column names
# print("Metadata:")
# print(default_of_credit_card_clients.metadata)

# Manually assign meaningful column names based on dataset documentation
column_names = [
    "LIMIT_BAL", "SEX", "EDUCATION", "MARRIAGE", "AGE",
    "PAY_1", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6",
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6",
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"
]

# Rename the columns in X
X.columns = column_names

In [3]:
merged_df = pd.concat([X, y], axis=1)

In [4]:
merged_df['age_group'] = merged_df['AGE'].apply(lambda x: 1 if 25 < x < 65 else 0)
age_group_column = merged_df.pop('age_group')  # Remove the column
merged_df.insert(8, 'age_group', age_group_column)  # Insert it at position 9

merged_df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,age_group,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,Y
0,20000,2,2,1,24,2,2,-1,0,-1,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,1,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,1,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,1,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [5]:
merged_df['MARRIAGE'].value_counts()

MARRIAGE
2    15964
1    13659
3      323
0       54
Name: count, dtype: int64

In [6]:
merged_df=merged_df[merged_df['MARRIAGE'].isin([1, 2])]

In [7]:
merged_df=merged_df[[
    "LIMIT_BAL", "SEX", "EDUCATION",
    "MARRIAGE", "AGE",
    "PAY_1", "PAY_3", "PAY_6","age_group",
    "BILL_AMT1", "BILL_AMT3", "BILL_AMT6",
    "PAY_AMT1", "PAY_AMT6","Y"
]]
merged_df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_3,PAY_6,age_group,BILL_AMT1,BILL_AMT3,BILL_AMT6,PAY_AMT1,PAY_AMT6,Y
0,20000,2,2,1,24,2,-1,-2,0,3913,689,0,0,0,1
1,120000,2,2,2,26,-1,0,2,1,2682,2682,3261,0,2000,1
2,90000,2,2,2,34,0,0,0,1,29239,13559,15549,1518,5000,0
3,50000,2,2,1,37,0,0,0,1,46990,49291,29547,2000,1000,0
4,50000,1,2,1,57,-1,-1,0,1,8617,35835,19131,2000,679,0

In [8]:
 # (1 = male; 2 = female).
merged_df['SEX'].value_counts()

SEX
2    17880
1    11743
Name: count, dtype: int64

In [9]:
 # (1 = married; 2 = single; 3 = others).
merged_df['MARRIAGE'].value_counts()

MARRIAGE
2    15964
1    13659
Name: count, dtype: int64

In [10]:
merged_df['age_group'].value_counts()

age_group
1    25661
0     3962
Name: count, dtype: int64

In [11]:
# # fetch dataset 
# bank_marketing = fetch_ucirepo(id=222) 
  
# # data (as pandas dataframes) 
# X = bank_marketing.data.features 
# y = bank_marketing.data.targets

In [12]:
# print("total length",len(X))

# merged_df = pd.concat([X, y], axis=1)
# merged_df.isna().sum()

In [13]:
# pd.unique(merged_df["previous"])

In [14]:
# merged_df = merged_df.drop(columns=['poutcome','contact','pdays'])
# merged_df=merged_df.dropna()
# # merged_df['y'] = merged_df['y'].map({'no': 0, 'yes': 1})

# merged_df.head()

In [15]:
merged_df['Y'].value_counts()

Y
0    23076
1     6547
Name: count, dtype: int64

In [16]:
print(len(merged_df))

29623

In [17]:
merged_df.isna().sum()

LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_3        0
PAY_6        0
age_group    0
BILL_AMT1    0
BILL_AMT3    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT6     0
Y            0
dtype: int64

In [18]:
merged_df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_3,PAY_6,age_group,BILL_AMT1,BILL_AMT3,BILL_AMT6,PAY_AMT1,PAY_AMT6,Y
0,20000,2,2,1,24,2,-1,-2,0,3913,689,0,0,0,1
1,120000,2,2,2,26,-1,0,2,1,2682,2682,3261,0,2000,1
2,90000,2,2,2,34,0,0,0,1,29239,13559,15549,1518,5000,0
3,50000,2,2,1,37,0,0,0,1,46990,49291,29547,2000,1000,0
4,50000,1,2,1,57,-1,-1,0,1,8617,35835,19131,2000,679,0

In [19]:
columns = list(merged_df.columns)
columns.remove("age_group") 
columns.remove("SEX") 
columns.insert(8, "SEX") 
columns.insert(9, "age_group") 
merged_df = merged_df[columns]
merged_df.head()

,LIMIT_BAL,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_3,PAY_6,BILL_AMT1,SEX,age_group,BILL_AMT3,BILL_AMT6,PAY_AMT1,PAY_AMT6,Y
0,20000,2,1,24,2,-1,-2,3913,2,0,689,0,0,0,1
1,120000,2,2,26,-1,0,2,2682,2,1,2682,3261,0,2000,1
2,90000,2,2,34,0,0,0,29239,2,1,13559,15549,1518,5000,0
3,50000,2,1,37,0,0,0,46990,2,1,49291,29547,2000,1000,0
4,50000,2,1,57,-1,-1,0,8617,1,1,35835,19131,2000,679,0

In [20]:
# merged_df['job'] = merged_df['job'].str.strip()
# merged_df['marital'] = merged_df['marital'].str.strip()
# merged_df['education'] = merged_df['education'].str.strip()
# merged_df['default'] = merged_df['default'].str.strip()
# merged_df['housing'] = merged_df['housing'].str.strip()
# merged_df['loan'] = merged_df['loan'].str.strip()
# merged_df['month'] = merged_df['month'].str.strip()
# merged_df['y'] = merged_df['y'].str.strip()
# merged_df.tail()

In [21]:
len(merged_df)

29623

In [22]:
merged_df['sex_ageGroup'] = merged_df['SEX'].astype(str) + '_' + merged_df['age_group'].astype(str)

# Step 2: Stratified Sampling for df1 (10,000 data points)
df1_sample, remaining_data = train_test_split(
    merged_df, test_size=(1 - 6000 / len(merged_df)), stratify=merged_df['sex_ageGroup'], random_state=42
)
df1_sample = df1_sample.drop(columns=['sex_ageGroup'])
df1_sample = df1_sample.reset_index(drop=True)
df1_sample

,LIMIT_BAL,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_3,PAY_6,BILL_AMT1,SEX,age_group,BILL_AMT3,BILL_AMT6,PAY_AMT1,PAY_AMT6,Y
0,450000,2,1,43,-2,-2,-2,7361,2,1,6982,7676,8692,6957,0
1,50000,1,2,26,0,0,2,44838,1,1,47121,46001,1769,1486,1
2,10000,2,1,50,0,0,-1,3664,1,1,6880,6195,1300,0,0
3,360000,2,2,28,-2,-2,0,0,1,1,0,8788,0,170027,0
4,150000,5,1,38,-2,-2,-2,0,2,1,1597,718,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,140000,1,1,34,-1,-2,-1,2574,2,1,0,840,0,1380,0
5996,80000,2,2,22,-1,-1,-1,1812,2,0,388,1913,390,1815,0
5997,360000,1,2,38,-1,-1,-1,1800,1,1,2722,2054,2413,2071,0
5998,360000,2,1,32,-1,-1,-1,942,1,1,33148,7090,3678,1193,0
5999,150000,4,2,32,0,0,0,159919,1,1,161192,146411,4019,5600,0

In [23]:
len(remaining_data)

23623

In [24]:
df2_sample, remaining_data = train_test_split(
    remaining_data, test_size=(1 - 10000 / len(remaining_data)), stratify=remaining_data['sex_ageGroup'], random_state=42
)
df2_sample = df2_sample.drop(columns=['sex_ageGroup'])

df2_sample = df2_sample.reset_index(drop=True)

df2_sample

,LIMIT_BAL,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_3,PAY_6,BILL_AMT1,SEX,age_group,BILL_AMT3,BILL_AMT6,PAY_AMT1,PAY_AMT6,Y
0,50000,2,1,29,0,0,0,39124,1,1,41220,44530,2000,2000,0
1,200000,2,1,56,0,0,0,195456,1,1,171784,189686,8007,0,0
2,120000,3,1,38,0,0,0,40538,1,1,58882,52533,1988,1500,0
3,30000,2,2,30,0,0,0,22221,1,1,24260,25763,1391,955,0
4,50000,2,2,27,1,0,0,-697,1,1,47194,50126,49900,469,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,140000,2,1,46,-1,-1,-1,264,2,1,264,264,1024,414,0
9996,130000,2,2,23,0,0,0,113900,2,0,105252,99525,5000,9000,0
9997,120000,1,2,27,0,0,0,110994,2,1,30212,32513,1471,1345,0
9998,500000,1,2,32,1,-1,0,-218,1,1,1267,167416,1000,8000,0
9999,360000,2,2,26,0,0,0,89635,1,1,75246,67271,3122,2256,0

In [25]:
len(df2_sample),len(df1_sample)

(10000, 6000)

In [26]:
len(remaining_data)

13623

In [27]:
dfs_2000 = []

while len(remaining_data) >= 2000:
    sample_2000, remaining_data = train_test_split(
        remaining_data, test_size=(1 - 2000 / len(remaining_data)), stratify=remaining_data['sex_ageGroup'], random_state=42
    )
    dfs_2000.append(sample_2000)

# Handle remaining data points (if any) as the last DataFrame
if len(remaining_data) > 0:
    dfs_2000.append(remaining_data)

dfs_2000 = [df.drop(columns=['sex_ageGroup']) for df in dfs_2000]
dfs_2000 = [df.reset_index(drop=True) for df in dfs_2000]

In [28]:
len(dfs_2000)

7

In [29]:
dfs_2000[0].head()

,LIMIT_BAL,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_3,PAY_6,BILL_AMT1,SEX,age_group,BILL_AMT3,BILL_AMT6,PAY_AMT1,PAY_AMT6,Y
0,210000,3,1,44,-2,-2,-2,1525,1,1,850,2694,800,1530,0
1,30000,2,1,42,0,0,2,27276,2,1,27699,30059,3671,869,0
2,80000,5,1,25,0,0,0,74180,2,0,74792,78862,3500,2784,0
3,260000,2,1,28,0,0,0,251811,2,1,143240,28736,9388,15000,0
4,500000,1,2,29,0,0,0,36051,2,1,33740,18740,2065,2000,0

In [30]:
for i in range(len(dfs_2000)):
    print(len(dfs_2000[i]))

2000
2000
2000
2000
1999
2000
1624

In [31]:
for i in range(len(dfs_2000)):
    dfs_2000[i].to_csv(f'../clients_data/raw_data/client_{i}.data', header=False, index=False)

# testing data

In [32]:
df2_sample.to_csv(f'../clients_data/raw_data/client_credit.test', header=False, index=False)

In [33]:
len(df2_sample)

10000

# pre_train raw data

In [34]:
df1_sample.to_csv(f'../clients_data/raw_data/client_data_pre_trained_model.data', header=False, index=False)

In [35]:
len(df1_sample)

6000

# group raw_data

In [36]:
df2_sample.head()

,LIMIT_BAL,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_3,PAY_6,BILL_AMT1,SEX,age_group,BILL_AMT3,BILL_AMT6,PAY_AMT1,PAY_AMT6,Y
0,50000,2,1,29,0,0,0,39124,1,1,41220,44530,2000,2000,0
1,200000,2,1,56,0,0,0,195456,1,1,171784,189686,8007,0,0
2,120000,3,1,38,0,0,0,40538,1,1,58882,52533,1988,1500,0
3,30000,2,2,30,0,0,0,22221,1,1,24260,25763,1391,955,0
4,50000,2,2,27,1,0,0,-697,1,1,47194,50126,49900,469,0

In [37]:
merge_df=df2_sample.copy()

In [38]:
male = merge_df.loc[(merge_df['SEX'] == 1)]
female = merge_df.loc[(merge_df['SEX'] == 2)]
age_group_1 = merge_df.loc[(merge_df['age_group'] == 1)]
age_group_0 = merge_df.loc[(merge_df['age_group'] == 0)]

print("Length: ",len(male),len(female),len(age_group_1),len(age_group_0))

Length:  3965 6035 8662 1338

In [39]:
# =====Testing=============
male.to_csv(f'../clients_data/raw_data/male.data', header=False, index=False)
female.to_csv(f'../clients_data/raw_data/female.data', header=False, index=False)
age_group_1.to_csv(f'../clients_data/raw_data/age_group_1.data', header=False, index=False)
age_group_0.to_csv(f'../clients_data/raw_data/age_group_0.data', header=False, index=False)

In [40]:
# ["male","female","age_group_1","age_group_0"]

# Subgroup raw_data

In [41]:
merge_df_train=df2_sample.copy()

In [42]:

male_agegroup1 = merge_df_train.loc[(merge_df_train['SEX'] == 1) & (merge_df_train['age_group'] == 1)]

male_agegroup0 = merge_df_train.loc[(merge_df_train['SEX'] == 1) & (merge_df_train['age_group'] == 0)]

female_agegroup1 = merge_df_train.loc[(merge_df_train['SEX'] == 2) & (merge_df_train['age_group'] == 1)]

female_agegroup0 = merge_df_train.loc[(merge_df_train['SEX'] == 2) & (merge_df_train['age_group'] == 0)]

print("Length: ",len(male_agegroup1),len(male_agegroup0),len(female_agegroup1),len(female_agegroup0))

Length:  3553 412 5109 926

In [43]:

male_agegroup1.to_csv(f'../clients_data/raw_data/male_agegroup1.data', header=False, index=False)
male_agegroup0.to_csv(f'../clients_data/raw_data/male_agegroup0.data', header=False, index=False)
female_agegroup1.to_csv(f'../clients_data/raw_data/female_agegroup1.data', header=False, index=False)
female_agegroup0.to_csv(f'../clients_data/raw_data/female_agegroup0.data', header=False, index=False)

In [44]:
# ["male_agegroup1","male_agegroup0","female_agegroup1","female_agegroup0"]

In [52]:
# train_df.to_csv("datasets/ADULT/credit.data", index=False,header=False,sep=',')
# test_df.to_csv("datasets/ADULT/credit.test", index=False,header=False,sep=',')