In [1]:
import pandas as pd
import os 
from sklearn.model_selection import train_test_split
from ucimlrepo import fetch_ucirepo 
import pandas as pd  
from sklearn.model_selection import train_test_split

In [2]:
# data1="../datasets/ADULT/adult.data"
# data2="../datasets/ADULT/adult.test"

In [3]:
# cols = [
#     'age',
#     'workclass',
#     'fnlwgt',
#     'education',
#     'education-num',
#     'marital-status',
#     'occupation',
#     'relationship',
#     'race',
#     'sex',
#     'capital-gain',
#     'capital-loss',
#     'hours-per-week',
#     'native-country',
#     'salary'
# ]
# df1= pd.read_csv(data1)
# df2 = pd.read_csv(data2, skiprows=1, header=None) # skip first row

# df1.columns = cols
# df2.columns = cols

In [4]:
# df1.head()

In [5]:
# df2.head()

In [6]:
# merged_df =pd.concat([df1, df2], axis=0)

# merged_df['workclass'] = merged_df['workclass'].str.strip()
# merged_df['education'] = merged_df['education'].str.strip()
# merged_df['marital-status'] = merged_df['marital-status'].str.strip()
# merged_df['occupation'] = merged_df['occupation'].str.strip()
# merged_df['relationship'] = merged_df['relationship'].str.strip()

# merged_df['race'] = merged_df['race'].str.strip()
# merged_df['sex'] = merged_df['sex'].str.strip()
# merged_df['native-country'] = merged_df['native-country'].str.strip()
# merged_df.tail()

In [7]:
# merged_df['salary'] = merged_df['salary'].str.replace('<=50K', '<=50K').str.replace('>50K', '>50K').str.replace(' ', '').str.replace('.', '')

In [8]:
# #Removing row with '?' 
# df_cleaned = merged_df[~merged_df.apply(lambda x: x.astype(str).str.contains('\?')).any(axis=1)]

# # View the cleaned DataFrame
# df_cleaned

In [9]:
# merged_df = df_cleaned.copy()

In [10]:
# merged_df.isnull().sum()

In [11]:
# merged_df

In [12]:
# pd.unique(merged_df["occupation"])

In [13]:
# merged_df.dropna(inplace=True)
# len(merged_df)

In [14]:

# fetch dataset 
adult = fetch_ucirepo(id=2) 

# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets 

print("total length::",len(X),"\n")

merged_df = pd.concat([X, y], axis=1)

print(merged_df.isna().sum())

merged_df=merged_df.dropna()

print(len(merged_df))

print(merged_df.isna().sum())

total length:: 48842

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
income              0
dtype: int64
47621
age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [15]:
merged_df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [16]:
merged_df['race_sex'] = merged_df['race'] + '_' + merged_df['sex']

# Step 2: Stratified Sampling for df1 (10,000 data points)
df1_sample, remaining_data = train_test_split(
    merged_df, test_size=(1 - 6000 / len(merged_df)), stratify=merged_df['race_sex'], random_state=42
)
df1_sample = df1_sample.drop(columns=['race_sex'])
df1_sample = df1_sample.reset_index(drop=True)
df1_sample

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,44,Local-gov,183850,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,56,United-States,<=50K.
1,42,Private,126319,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Female,0,0,35,United-States,<=50K.
2,32,Private,50753,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K.
3,27,Private,144063,10th,6,Never-married,Craft-repair,Unmarried,White,Male,0,0,75,United-States,<=50K.
4,31,Local-gov,209103,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,3464,0,45,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,27,Private,220931,HS-grad,9,Divorced,Adm-clerical,Unmarried,White,Female,0,0,32,United-States,<=50K.
5996,43,Private,163847,Bachelors,13,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,>50K
5997,24,State-gov,27939,Some-college,10,Married-civ-spouse,Other-service,Husband,Asian-Pac-Islander,Male,0,0,24,?,<=50K
5998,47,Private,111797,Some-college,10,Never-married,Other-service,Not-in-family,Black,Female,0,0,35,Outlying-US(Guam-USVI-etc),<=50K
5999,26,Private,153169,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States,<=50K.

In [17]:
len(remaining_data)

41621

In [18]:
df2_sample, remaining_data = train_test_split(
    remaining_data, test_size=(1 - 10000 / len(remaining_data)), stratify=remaining_data['race_sex'], random_state=42
)
df2_sample = df2_sample.drop(columns=['race_sex'])

df2_sample = df2_sample.reset_index(drop=True)

df2_sample

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,35,Private,374524,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,75,United-States,>50K
1,75,Self-emp-not-inc,31428,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,3456,0,40,United-States,<=50K
2,34,Private,144798,Some-college,10,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
3,49,Private,189792,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,<=50K.
4,18,State-gov,272918,HS-grad,9,Never-married,Adm-clerical,Own-child,Black,Male,0,0,15,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,26,Private,167350,12th,8,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
9996,33,Private,55291,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
9997,41,Private,149576,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K.
9998,37,Private,549174,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,>50K
9999,32,?,119522,Bachelors,13,Divorced,?,Not-in-family,White,Male,0,0,50,United-States,<=50K

In [19]:
len(df2_sample),len(df1_sample)

(10000, 6000)

In [20]:
len(remaining_data)

31621

In [21]:
dfs_2000 = []

while len(remaining_data) >= 2000:
    sample_2000, remaining_data = train_test_split(
        remaining_data, test_size=(1 - 2000 / len(remaining_data)), stratify=remaining_data['race_sex'], random_state=42
    )
    dfs_2000.append(sample_2000)

# Handle remaining data points (if any) as the last DataFrame
if len(remaining_data) > 0:
    dfs_2000.append(remaining_data)

dfs_2000 = [df.drop(columns=['race_sex']) for df in dfs_2000]
dfs_2000 = [df.reset_index(drop=True) for df in dfs_2000]

In [22]:
len(dfs_2000)

16

In [23]:
dfs_2000[0].head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,80312,Assoc-voc,11,Never-married,Adm-clerical,Not-in-family,White,Female,4865,0,40,United-States,<=50K
1,43,Local-gov,98130,Bachelors,13,Divorced,Prof-specialty,Own-child,White,Female,0,0,39,United-States,<=50K
2,33,Private,178107,Bachelors,13,Never-married,Craft-repair,Own-child,White,Male,0,0,20,United-States,<=50K
3,32,Private,186269,HS-grad,9,Never-married,Other-service,Own-child,White,Male,2907,0,35,United-States,<=50K.
4,38,Private,190759,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K

In [24]:
for i in range(len(dfs_2000)):
    print(len(dfs_2000[i]))

2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
1999
2000
2000
1622

In [25]:
for i in range(len(dfs_2000)):
    dfs_2000[i].to_csv(f'../clients_data/raw_data/client_{i}.data', header=False, index=False)

In [26]:
# df2_sample[:1000].to_csv(f'../clients_data/raw_data/client_adult.test', header=False, index=False)

# tesing data

In [27]:
df2_sample.to_csv(f'../clients_data/raw_data/client_adult.test', header=False, index=False)

# pretrain_raw_data

In [28]:
df1_sample.to_csv(f'../clients_data/raw_data/client_data_pre_trained_model.data', header=False, index=False)

In [29]:
len(df1_sample)

6000

# group _raw_data

In [30]:
merge_df=df2_sample.copy()

In [31]:
men = merge_df.loc[(merge_df['sex'] == "Male")]
women = merge_df.loc[(merge_df['sex'] == "Female")]
white = merge_df.loc[(merge_df['race'] == "White")]
black = merge_df.loc[(merge_df['race'] == "Black")]

print("Length: ",len(men),len(women),len(white),len(black))

Length:  6705 3295 8564 953

In [32]:
# =====Testing=============
men.to_csv(f'../clients_data/raw_data/male.data', header=False, index=False)
women.to_csv(f'../clients_data/raw_data/female.data', header=False, index=False)
white.to_csv(f'../clients_data/raw_data/white.data', header=False, index=False)
black.to_csv(f'../clients_data/raw_data/black.data', header=False, index=False)

# Subgroup raw_data

In [33]:
merge_df_train=df2_sample.copy()

In [34]:
#White Men
WM = merge_df_train.loc[(merge_df_train['sex'] == "Male") & (merge_df_train['race'] == "White")]
#Black Men
BM = merge_df_train.loc[(merge_df_train['sex'] == "Male") & (merge_df_train['race'] == "Black")]
#white Women
WW = merge_df_train.loc[(merge_df_train['sex'] == "Female") & (merge_df_train['race'] == "White")]
#Black Women
BW = merge_df_train.loc[(merge_df_train['sex'] == "Female") & (merge_df_train['race'] == "Black")]

print("Length: ",len(WM),len(BM),len(WW),len(BW))

Length:  5912 482 2652 471

In [35]:

WW.to_csv(f'../clients_data/raw_data/WW.data', header=False, index=False)
WM.to_csv(f'../clients_data/raw_data/WM.data', header=False, index=False)
BW.to_csv(f'../clients_data/raw_data/BW.data', header=False, index=False)
BM.to_csv(f'../clients_data/raw_data/BM.data', header=False, index=False)